---

- name: Install requirements
  apt: pkg={{item}}
  with_items:
      - postfix
      - ca-certificates
      - mailutils

- name: Install postfix-pcre
  apt: pkg=postfix-pcre
  when: postfix_rewrite_sender_address != ""
